{{- if and .Values.secret.create (not .Values.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loadify.secretName" . }}
  labels:
    {{- include "loadify.labels" . | nindent 4 }}
type: Opaque
stringData:
  LOADIFY_POSTGRES_DSN: {{ .Values.secret.postgresDSN | quote }}
  LOADIFY_JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  LOADIFY_FEISHU_APP_ID: {{ .Values.secret.feishuAppID | quote }}
  LOADIFY_FEISHU_APP_SECRET: {{ .Values.secret.feishuAppSecret | quote }}
  LOADIFY_ADMIN_EMAIL: {{ .Values.secret.adminEmail | quote }}
  LOADIFY_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
{{- end }}
