{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "loadify.serviceAccountName" . }}
  labels:
    {{- include "loadify.labels" . | nindent 4 }}
{{- end }}
