{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loadify.fullname" . }}-web
  labels:
    {{- include "loadify.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      {{- include "loadify.selectorLabels" (dict "ctx" . "component" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "loadify.selectorLabels" (dict "ctx" . "component" "web") | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "loadify.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: {{ include "loadify.image" (dict "ctx" . "component" "web") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - { name: http, containerPort: {{ .Values.web.port }} }
          env:
            - { name: NEXT_PUBLIC_API_BASE, value: {{ .Values.config.apiBase | quote }} }
            - { name: PORT, value: {{ .Values.web.port | quote }} }
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "loadify.fullname" . }}-web
  labels:
    {{- include "loadify.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "loadify.selectorLabels" (dict "ctx" . "component" "web") | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.web.port }}, targetPort: http }
{{- end }}
