ALTER TABLE runs ADD COLUMN IF NOT EXISTS name text NOT NULL DEFAULT '';

ALTER TABLE runs ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE test_definitions ADD COLUMN IF NOT EXISTS created_by uuid REFERENCES users(id) ON DELETE SET NULL
